version: '3.4'

services:
  app:
    container_name: plex_app
    image: plexinc/pms-docker:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '32400'
      - '3005' 
      - '8324'
      - '32469'
      - '1900'
      - '32410'
      - '32412'
      - '32413'
      - '32414'
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - app
    environment:
      - PLEX_UID=120
      - PLEX_GID=127
    volumes:
      - config:/config
      - photos:/data/Photos
      - television:/data/Television
      - ota_television:/data/OTA Television
      - movies:/data/Movies
      - music:/data/Music
    devices:
      - "/dev/dvb/adapter0/demux0:/dev/dvb/adapter0/demux0"
      - "/dev/dvb/adapter0/dvr0:/dev/dvb/adapter0/dvr0"
      - "/dev/dvb/adapter0/frontend0:/dev/dvb/adapter0/frontend0"
      - "/dev/dvb/adapter0/net0:/dev/dvb/adapter0/net0"

      - "/dev/dvb/adapter1/demux0:/dev/dvb/adapter1/demux0"
      - "/dev/dvb/adapter1/dvr0:/dev/dvb/adapter1/dvr0"
      - "/dev/dvb/adapter1/frontend0:/dev/dvb/adapter1/frontend0"
      - "/dev/dvb/adapter1/net0:/dev/dvb/adapter1/net0"

      - "/dev/dvb/adapter2/demux0:/dev/dvb/adapter2/demux0"
      - "/dev/dvb/adapter2/dvr0:/dev/dvb/adapter2/dvr0"
      - "/dev/dvb/adapter2/frontend0:/dev/dvb/adapter2/frontend0"
      - "/dev/dvb/adapter2/net0:/dev/dvb/adapter2/net0"

      - "/dev/dvb/adapter3/demux0:/dev/dvb/adapter3/demux0"
      - "/dev/dvb/adapter3/dvr0:/dev/dvb/adapter3/dvr0"
      - "/dev/dvb/adapter3/frontend0:/dev/dvb/adapter3/frontend0"
      - "/dev/dvb/adapter3/net0:/dev/dvb/adapter3/net0"
  plexpy_app:
    container_name: plexpy_app
    image: linuxserver/plexpy:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '8181'
    networks:
      - app
    environment:
      - PGID=127
      - PUID=120
    volumes:
      - plexpy:/config
      - config:/logs:ro
networks:
  app:
    driver: 'bridge'
volumes:
  plexpy:
  config:
  photos:
  television:
  ota_television:
  movies:
  music:
