version: "3.4"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - home:/minecraft
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2"
          memory: 2048M
volumes:
  home:
    name: minecraft
