version: '3.4'

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    stdin_open: true
    tty: true
    hostname: 'gitlab.tburgh.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.tburgh.net'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 8000:80
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
